### ISSUE TITLE
packrat::restore() installation fails

### ISSUE THREAD

**Issue by mikerspencer** [jcolomb/HCS_analysis#18]
Running on local machine: Ubuntu 18.04 with R 3.6.3. I get the following error during `packrat::restore()`:

    Error: package 'plogr' 0.1-1 was found, but >= 0.2.0 is required by 'dplyr'

Is this because packrat has a snapshot of R 3.6.1?

This is issue was picked up as part of the [JOSS review](https://github.com/openjournals/joss-reviews/issues/2282).

**Comment by aj2duncan** [comment]
I have a similar issue, also picked up as part of openjournals/joss-reviews#2282. 

```r
packrat::restore()
```
```

The command failed with output:
* installing *source* package 'nloptr' ...
** package 'nloptr' successfully unpacked and MD5 sums checked
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
C:/Rtools/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG          -O2 -Wall  -mtune=core2 -c dummy.cpp -o dummy.o
C:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG       -I"/x64/include"   -O2 -Wall  -std=gnu99 -mtune=core2 -c init_nloptr.c -o init_nloptr.
In addition: Warning messages:
1: In packrat::restore() :
  The most recent snapshot was generated using R version 3.6.1
2: In untar(src, exdir = target, compressed = "gzip") :
  argument 'compressed' is ignored for the internal method
3: In untar(src, compressed = "gzip", list = TRUE) :
  argument 'compressed' is ignored for the internal method
```
```r
sessionInfo()
```
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3   tools_3.6.3      packrat_0.4.8-56
```

As advised I then uncommented and ran the necessary lines from  *Installation_Rpackages.R*. The command 
```r
devtools::install_github('jcolomb/osfr')
```
also produced an error:
```
Error: package or namespace load failed for 'osfr' in namespaceExport(ns, exports):
 undefined exports: welcome
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'osfr' in namespaceExport(ns, exports):
 undefined exports: welcome
Error: loading failed
Execution halted
```

All this aside, the app runs and I will keep testing to see if the app itself produces any errors.

**Comment by jcolomb** [comment]
sorry to be slow on  this, I will try to look at it again (I did have problems I thought were cleared)

**Comment by jcolomb** [comment]
the osf package is not necessary anymore, I will delete it from the installation file

**Comment by jcolomb** [comment]
still working on packrat...
osfr package actually necessary for metadata upload, I made some changes in the master branch to cope with the CRAN version of osfr.

**Comment by aj2duncan** [comment]
Hi @jcolomb, just wondering if there had been any progress on this yet? Thanks.

**Comment by jcolomb** [comment]
still working on that, tried to redo everything from scratch, but it still gives error. Starting to think packrat is just a waste of time grrrr

**Comment by jcolomb** [comment]
trying renv migration. let's see if that works better.

**Comment by jcolomb** [comment]
renv seems more stable, will still make some test to #21

**Comment by jcolomb** [comment]
It is not running if using R4.0, can you confirm it works with r3.6?

**Comment by aj2duncan** [comment]
I seem to have `renv::restore()` success with R.3.6.3 but with some warnings.

```
Warning messages:
1: In read.dcf(file, ...) :
  Line starting 'randomForest, ...' is malformed!
2: In read.dcf(file, ...) :
  Line starting 'randomForest, ...' is malformed!
3: In read.dcf(file, ...) :
  Line starting 'randomForest, ...' is malformed!
```

**Comment by jcolomb** [comment]
thank you for testing, happy to see this working.
(The warning comes from the "document" file, which may be a remnant of packrat.)

can we set this closed by #21 ?

**Comment by aj2duncan** [comment]
I'm happy to close this but I think we might need to get an opinion from @mikerspencer

**Comment by mikerspencer** [comment]
My plan is to finish the review this week - I've a little more time than the past few months. Fingers crossed!

**Comment by mikerspencer** [comment]
Does packrat::restore run with R 4 yet? I'm trying today but getting an error between dplyr and plogr.

**Comment by jcolomb** [comment]
I could not make packrat to work and move the project to the novel renv package environment.
I did not try to make it work with R4.0, so the installation code just install the packages for R4.0 and use renv for R3.6.

This is in the https://github.com/jcolomb/HCS_analysis/tree/joss_reviewanswers branch.

**Comment by mikerspencer** [comment]
I'm pausing my review while the file name errors are fixed (https://github.com/jcolomb/HCS_analysis/issues/30). Not currently possible to run the app while they exist.

**Comment by jcolomb** [comment]
I hope everything is fixed now. You may need to clone the repository again, as git is not really good with case sensitivity.

**Comment by mikerspencer** [comment]
All seems good now - less packages also makes loading quicker.
