### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by aj2duncan** [jcolomb/HCS_analysis#19]
Hi @jcolomb, 

As part of the review (openjournals/joss-reviews#2282) I think that you need to add some detail to your contribution guide on the repo. You have already stated that contributions are welcome but I wonder if adding a contributing.md (demo [here](https://github.com/tidyverse/dplyr/blob/master/.github/CONTRIBUTING.md)) might help others.

Thanks,

Andrew

**Comment by jcolomb** [comment]
good point, it was not thought as an open project in the beginning, but it should now.

**Comment by jcolomb** [comment]
done: https://github.com/jcolomb/HCS_analysis/commit/31de3a1ba4c362ca0e4037691567e66d4223cc50.

please comment if you find it not sufficient

**Comment by aj2duncan** [comment]
Hi @jcolomb, that looks just great. Thanks.
