### ISSUE TITLE
Clarification of uploading metadata to OSF

### ISSUE THREAD

**Issue by aj2duncan** [jcolomb/HCS_analysis#20]
Hi @jcolomb, 

As part of [joss-review](https://github.com/openjournals/joss-reviews/issues/2282) I was wondering if the upload of metadata to osf needs to be made clearer. For instance the osf [documentation](https://docs.ropensci.org/osfr/articles/auth) states that an OSF PAT is required. You are already using one but I needed to look through the code to find this? Also wondering what @mikerspencer thinks about this?

**Comment by jcolomb** [comment]
good point, especially since I just had to change the code to be able to make the upload working with the new osfr package.

**Comment by jcolomb** [comment]
I added some information in the readme file, is it the good place or would you better see it also somewhere else?

**Comment by aj2duncan** [comment]
I like what you've put in the Readme but wonder if some information should also go in `Metadata_information/Readme.md` too. I was also wondering if some screen shots might help users too - I found the main app quite intuitive to use, the metadata one slightly less so - might just be me though.

**Comment by jcolomb** [comment]
The metadata one is indeed a bit more complex, and I spent less time on it, too. Thanks for the feedback.

**Comment by aj2duncan** [comment]
Hi @jcolomb, just wondering if you had decided to add any other additional changes to the documentation? Thanks.

**Comment by jcolomb** [comment]
yeah, sorry, got this down my todo list.. I still remember having made a video, but cannot find it anymore.

That is quite some work, but I will get to it next week.

**Comment by jcolomb** [comment]
Doing this lead to the discovery of some bugs. I hope they are all taken care of in #23. 
Will now finish to work on the documentation.

In addition, working with a different dataset and trying to push it online, made me discover other problems in the analysis application itself. I will run extra test on #24

**Comment by jcolomb** [comment]
@aj2duncan #27 is ready for review, many changes were done to the documentation and to the app.

**Comment by aj2duncan** [comment]
Thanks @jcolomb, I will try to have a look as soon as I can.

**Comment by aj2duncan** [comment]
Hi @jcolomb,

I think that the documentation, particularly on the metadata is far more comprehensive and will undoubtedly make it easier for users. 

However, I'm getting a few additional errors. First on the test and upload app using the Ro_testdata and pressing the *Test_metadata* button produces the following error:

```
[1] "some files are not grabbed by the metadata, are some animals missing?"
Joining, by = "filepath"
Joining, by = "filepath"
Warning: Unknown or uninitialised column: `sourcce_data`.
Warning: Error in if: argument is of length zero
```

In the analyse data app, choosing the time windows and the multidimensional analysis seems to work well. However, there seems to be a problem with the summary reports. First, there is an error produced on start up. I think that this will be a shiny artefact and not actually have any effect on performance. 

![image](https://user-images.githubusercontent.com/10415752/93027303-ea08c700-f603-11ea-99ed-11d9bc91536e.png)

and trying to produce the hourly summary data plots produces this error

```
  Warning: Error in pdf: cannot open file '../data/Ro_testdata/BSeq_analyserfatal: not a git repository (or any of the parent directories): .git/hourly_plotting_corrected.pdf'
```

Note that I downloaded the directory as a zip file rather than cloning it.

**Comment by jcolomb** [comment]
Test_metadata button error: I cannot reproduce the problem, I also cannot find "sourcce_data" text anywhere in my downloaded version. Maybe there was a problem during download or you changed something inadvertently after the download (it seems an extra "c" was introduced somewhere...) ?


The typo was indeed there in my version too, I have no clue why it worked on my side. thanks

**Comment by jcolomb** [comment]
I added a default plot to avoid the Erro: no applicable method... at startup.
I added a default version number for cases the git repository is downloaded and not cloned, this should allow the software to save things at a right place, I will now check whether the error is gone.

**Comment by jcolomb** [comment]
After some cleaning of data left over by older version of the data/software, it seems that everything is now working fine.
(need to use the https://github.com/jcolomb/HCS_analysis/tree/joss_reviewanswers version)

**Comment by aj2duncan** [comment]
Hi @jcolomb, thanks for the fixes. 

The analyse app is working fine. Still having the same issue with the metadata app but I've also found the problem (and I apologise as I should have noticed the line number reported before). There is a typo on line 392 of the shiny app file. This is where `sourcce_data` was coming from. Fixing the typo allows it to work and everything seems to be working at least for some of the datasets. 

Choosing the Rosenmund dataset got me the following error

```
Warning: Error in : 'NA/rosenmund_2015/metadata/rosenmund2015_meta_all.csv' does not exist in current working directory
```

Do you want to allow all the datasets to be testable by the metadata app?

**Comment by jcolomb** [comment]
It seems you tried to look at a dataset that you  have not provided. I added a message in the analysis app for dataset one has to provide locally. 

I added a small message in the metadata app too.

**Comment by aj2duncan** [comment]
Hi @jcolomb, 

Thanks for the additional note (btw small typo in column). I think your walkthrough of everything on the metadata README is very clear but I wonder if you might want to consider adding an additional message for the user. 

From my reading of things the dropdown for projects to analyse is produced from the `Project_metadata.csv` file which are the entries from the osf. Some of these datasets are also stored (at least partially) locally - R0_testdata, Steele07_HD and Ro_testdata_mbr. So a user can click *test_metadata* on one of those datasets and the app will run but if the dataset doesn't exist (any of the others), it will quit with an error. I would suggest that the user should get some sort of message - rather than the app quitting. 

However, the app does function as you intended so I'm happy to close this issue.
