### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aj2duncan** [jcolomb/HCS_analysis#22]
Hi @jcolomb,

As part of openjournals/joss-reviews#2282 I think that you need some additional documentation on the functionality of the shiny apps. This is linked with #20. The info in the paper is a little clearer than in the README but I'm still finding it a little difficult to navigate my way around. 

The screen shot and visual abstract in the paper could be included in the documentation and as with #20 I think that there needs to be a clear process for a new user to follow. I guess the process will be dependent on whether they need to upload metadata to osf first. 

Thanks.

**Comment by jcolomb** [comment]
Thank you, I hope to get some time to start this today.

**Comment by aj2duncan** [comment]
As far as I'm concerned this can be closed as the documentation is much improved.
