### ISSUE TITLE
Softwareheader.R is sourced twice in shiny__Analyse_data/app.R

### ISSUE THREAD

**Issue by mikerspencer** [jcolomb/HCS_analysis#29]
Softwareheader.R is sourced twice in shiny__Analyse_data/app.R

Consider using a `global.R` if there are things that need to be available across environments.

See <https://shiny.rstudio.com/articles/scoping.html>

**Comment by jcolomb** [comment]
just a non-used call to Softwareheader.R, deleted in #32
