### ISSUE TITLE
Inconsistency in file names

### ISSUE THREAD

**Issue by mikerspencer** [jcolomb/HCS_analysis#30]
There is a general inconsistency in file names (some end `.r` some `.R`), which is causing problems for file loading. e.g. https://github.com/jcolomb/HCS_analysis/issues/28.

Another example: line 447 in `shiny__Analyse_data/app.R` is `source ("Rcode/get_behav_gp.r")`, but the file is `Rcode/get_behav_gp.R`.

Consistent file names would help avoid these mistakes.

**Comment by jcolomb** [comment]
hopefully fixed with #31 #32

**Comment by danielskatz** [comment]
@mikerspencer - can you confirm this is fixed?  If so, you can continue your review in https://github.com/openjournals/joss-reviews/issues/2282 and @jcolomb can mark this as closed

**Comment by mikerspencer** [comment]
Yep, app loads now - great work!
