### ISSUE TITLE
error from missing reports/empty.html

### ISSUE THREAD

**Issue by mikerspencer** [jcolomb/HCS_analysis#37]
Running `shiny::runApp('analysis/shiny__Analyse_data')` from line 19 in the readme, generates a warning:

    Warning in file(con, "r") :
      cannot open file 'reports/empty.html': No such file or directory

Submitted as part of JOSS review: https://github.com/openjournals/joss-reviews/issues/2282

**Comment by jcolomb** [comment]
Are you using the `testing` branch ? I do not have that error on my side.
